version: "3.9"
services:
  web:
    build:
        context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  redis:
    image: "redis:alpine"
  db:
    image: mysql:5.7
    command: --init-file /usr/src/app/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw123
      MYSQL_DATABASE: web
      MYSQL_USER: usr
      MYSQL_PASSWORD: usr123demo
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/usr/src/app/init.sql
volumes:
  db_data: {}